## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: 1.1

script:
   - julia -e 'if VERSION >= v"0.7.0-" using Pkg; end; Pkg.clone(pwd()); Pkg.build("QDLDL"); Pkg.test("QDLDL"; coverage=true)';

after_success:
  # push coverage results to Codecov
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg; end; cd(Pkg.dir("QDLDL")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
